
import { Contact, InventoryItem, Job, JobTemplate, Kit, StockMovement } from './types';

export const INITIAL_CONTACTS: Contact[] = [
  { id: 'c1', name: 'John Doe', type: 'Plumber', email: 'john@plumbpro.com', phone: '555-0101' },
  { id: 'c2', name: 'Jane Smith', type: 'Plumber', email: 'jane@plumbpro.com', phone: '555-0102' },
  { id: 's1', name: 'PlumbSupply Co', type: 'Supplier', email: 'sales@plumbsupply.com', phone: '555-0500', company: 'PlumbSupply' },
  { id: 's2', name: 'DrainTech Tools', type: 'Supplier', email: 'info@draintech.com', phone: '555-0600', company: 'DrainTech' },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: 'i1', name: '15mm Copper Pipe (3m)', category: 'Piping', price: 24.50, quantity: 45, reorderLevel: 20, supplierId: 's1', supplierCode: 'CP-15-3M', locationStock: [] },
  { id: 'i2', name: 'Standard S-Trap', category: 'Fittings', price: 8.95, quantity: 12, reorderLevel: 15, supplierId: 's1', supplierCode: 'STRAP-STD', locationStock: [] },
  { id: 'i3', name: 'Plumber Putty 500g', category: 'Consumables', price: 5.20, quantity: 30, reorderLevel: 10, supplierId: 's2', supplierCode: 'PUT-500', locationStock: [] },
  { id: 'i4', name: 'Drain Snake - Industrial', category: 'Tools', price: 450.00, quantity: 3, reorderLevel: 2, supplierId: 's2', supplierCode: 'DS-IND-X', locationStock: [] },
  { id: 'i5', name: 'L-Shaped Elbow 15mm', category: 'Fittings', price: 1.25, quantity: 150, reorderLevel: 50, supplierId: 's1', supplierCode: 'ELB-15-L', locationStock: [] },
];

export const INITIAL_JOBS: Job[] = [
  { 
    id: 'j1', 
    title: 'Main Street Leak Repair', 
    builder: 'Skyline Homes',
    jobType: 'Repair', 
    assignedWorkerIds: ['c1'], 
    status: 'Scheduled', 
    date: '2024-06-15', 
    allocatedItems: [],
    isPicked: false 
  },
  { 
    id: 'j2', 
    title: 'West Side Bathroom Install', 
    builder: 'Private Owner',
    jobType: 'Installation', 
    assignedWorkerIds: ['c2', 'c1'], 
    status: 'In Progress', 
    date: '2024-06-10', 
    allocatedItems: [{ itemId: 'i1', quantity: 5 }],
    isPicked: true 
  },
];

export const JOB_TEMPLATES: JobTemplate[] = [
  {
    id: 't1',
    name: 'Basic Leak Repair Kit',
    items: [
      { itemId: 'i1', quantity: 1 },
      { itemId: 'i3', quantity: 1 },
      { itemId: 'i5', quantity: 4 },
    ]
  },
  {
    id: 't2',
    name: 'Standard Basin Install',
    items: [
      { itemId: 'i1', quantity: 2 },
      { itemId: 'i2', quantity: 1 },
      { itemId: 'i3', quantity: 1 },
      { itemId: 'i5', quantity: 2 },
    ]
  }
];

export const DEFAULT_KITS: Kit[] = [
  {
    id: '1',
    name: 'Standard Tap Replacement',
    description: 'Complete kit for replacing kitchen or bathroom taps',
    kitType: 'repair',
    category: 'Kitchen',
    status: 'active',
    color: '#10B981',
    icon: 'Droplet',
    applicableJobTypes: ['Tap Repair', 'Kitchen Renovation'],
    items: [
      { id: 'i1', itemType: 'inventory', inventoryItemId: '1', itemName: 'Flexi Hose 500mm', quantity: 2, unit: 'EA', unitCost: 12.5, unitSellPrice: 25, lineCostTotal: 25, lineSellTotal: 50, isOptional: false, isConsumable: true, sortOrder: 1 },
      { id: 'i2', itemType: 'inventory', inventoryItemId: '2', itemName: 'Thread Seal Tape', quantity: 1, unit: 'ROLL', unitCost: 2.5, unitSellPrice: 5, lineCostTotal: 2.5, lineSellTotal: 5, isOptional: false, isConsumable: true, sortOrder: 2 },
      { id: 'i3', itemType: 'labor', laborType: 'Licensed Plumber', itemName: 'Labor - Tap Replacement', quantity: 1, unit: 'HR', unitCost: 45, unitSellPrice: 95, lineCostTotal: 45, lineSellTotal: 95, isOptional: false, isConsumable: true, sortOrder: 3 },
    ],
    totalCostPrice: 72.5,
    totalSellPrice: 150,
    totalLaborHours: 1,
    defaultMarkupPercentage: 50,
    usageCount: 45,
    lastUsedAt: '2026-01-28T10:00:00Z',
    averageJobProfit: 77.5,
    tags: ['common', 'quick', 'tapware'],
    version: 1,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-12-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Hot Water System Install - Electric 250L',
    description: 'Full installation kit for 250L electric hot water system',
    kitType: 'installation',
    category: 'Hot Water',
    status: 'active',
    color: '#F59E0B',
    icon: 'Flame',
    applicableJobTypes: ['Hot Water Installation', 'Replacement'],
    items: [
      { id: 'i1', itemType: 'inventory', itemName: 'HWC 250L Electric', quantity: 1, unit: 'EA', unitCost: 850, unitSellPrice: 1200, lineCostTotal: 850, lineSellTotal: 1200, isOptional: false, isConsumable: true, sortOrder: 1 },
      { id: 'i2', itemType: 'inventory', itemName: 'Cold Water Isolator', quantity: 1, unit: 'EA', unitCost: 25, unitSellPrice: 45, lineCostTotal: 25, lineSellTotal: 45, isOptional: false, isConsumable: true, sortOrder: 2 },
      { id: 'i3', itemType: 'inventory', itemName: 'TPR Valve', quantity: 1, unit: 'EA', unitCost: 65, unitSellPrice: 110, lineCostTotal: 65, lineSellTotal: 110, isOptional: false, isConsumable: true, sortOrder: 3 },
      { id: 'i4', itemType: 'labor', laborType: 'Licensed Plumber', itemName: 'Labor - HWC Install', quantity: 3, unit: 'HR', unitCost: 45, unitSellPrice: 95, lineCostTotal: 135, lineSellTotal: 285, isOptional: false, isConsumable: true, sortOrder: 4 },
      { id: 'i5', itemType: 'labor', laborType: 'Electrician', itemName: 'Electrical Connection', quantity: 1, unit: 'HR', unitCost: 85, unitSellPrice: 150, lineCostTotal: 85, lineSellTotal: 150, isOptional: true, isConsumable: true, sortOrder: 5 },
    ],
    variations: [
      { id: 'v1', name: 'Standard', description: 'Standard installation', costMultiplier: 1.0 },
      { id: 'v2', name: 'Premium', description: 'Premium valve and fittings', costMultiplier: 1.15 },
    ],
    totalCostPrice: 1160,
    totalSellPrice: 1790,
    totalLaborHours: 4,
    defaultMarkupPercentage: 35,
    usageCount: 23,
    lastUsedAt: '2026-01-25T14:30:00Z',
    averageJobProfit: 630,
    tags: ['hot-water', 'installation', 'electric'],
    version: 2,
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2025-11-15T00:00:00Z',
  },
  {
    id: '3',
    name: 'Blocked Drain - Standard Clear',
    description: 'Standard drain clearing kit for minor blockages',
    kitType: 'repair',
    category: 'Drainage',
    status: 'active',
    color: '#6366F1',
    icon: 'Pipeline',
    applicableJobTypes: ['Blocked Drain', 'Emergency Callout'],
    items: [
      { id: 'i1', itemType: 'inventory', itemName: 'Drain Machine - Small', quantity: 1, unit: 'HR', unitCost: 25, unitSellPrice: 45, lineCostTotal: 25, lineSellTotal: 45, isOptional: false, isConsumable: false, sortOrder: 1 },
      { id: 'i2', itemType: 'inventory', itemName: 'Drain Camera Inspection', quantity: 1, unit: 'EA', unitCost: 85, unitSellPrice: 150, lineCostTotal: 85, lineSellTotal: 150, isOptional: true, isConsumable: true, sortOrder: 2 },
      { id: 'i3', itemType: 'labor', laborType: 'Licensed Plumber', itemName: 'Labor - Drain Clear', quantity: 1.5, unit: 'HR', unitCost: 45, unitSellPrice: 95, lineCostTotal: 67.5, lineSellTotal: 142.5, isOptional: false, isConsumable: true, sortOrder: 3 },
    ],
    totalCostPrice: 177.5,
    totalSellPrice: 337.5,
    totalLaborHours: 1.5,
    defaultMarkupPercentage: 60,
    usageCount: 67,
    lastUsedAt: '2026-02-01T09:15:00Z',
    averageJobProfit: 160,
    tags: ['drainage', 'emergency', 'common'],
    version: 1,
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2025-10-20T00:00:00Z',
  },
  {
    id: '4',
    name: 'Bathroom Renovation - Full',
    description: 'Complete plumbing package for full bathroom renovation',
    kitType: 'installation',
    category: 'Bathroom',
    status: 'active',
    color: '#3B82F6',
    icon: 'Bath',
    applicableJobTypes: ['Bathroom Renovation', 'New Build'],
    items: [
      { id: 'i1', itemType: 'inventory', itemName: 'Shower Mixer', quantity: 1, unit: 'EA', unitCost: 180, unitSellPrice: 280, lineCostTotal: 180, lineSellTotal: 280, isOptional: false, isConsumable: true, sortOrder: 1 },
      { id: 'i2', itemType: 'inventory', itemName: 'Vanity Basin Set', quantity: 1, unit: 'EA', unitCost: 220, unitSellPrice: 350, lineCostTotal: 220, lineSellTotal: 350, isOptional: false, isConsumable: true, sortOrder: 2 },
      { id: 'i3', itemType: 'inventory', itemName: 'Toilet Suite', quantity: 1, unit: 'EA', unitCost: 350, unitSellPrice: 550, lineCostTotal: 350, lineSellTotal: 550, isOptional: false, isConsumable: true, sortOrder: 3 },
      { id: 'i4', itemType: 'inventory', itemName: 'Floor Waste Grate', quantity: 1, unit: 'EA', unitCost: 45, unitSellPrice: 75, lineCostTotal: 45, lineSellTotal: 75, isOptional: false, isConsumable: true, sortOrder: 4 },
      { id: 'i5', itemType: 'labor', laborType: 'Licensed Plumber', itemName: 'Rough-in Labor', quantity: 8, unit: 'HR', unitCost: 45, unitSellPrice: 95, lineCostTotal: 360, lineSellTotal: 760, isOptional: false, isConsumable: true, sortOrder: 5 },
      { id: 'i6', itemType: 'labor', laborType: 'Licensed Plumber', itemName: 'Fit-off Labor', quantity: 6, unit: 'HR', unitCost: 45, unitSellPrice: 95, lineCostTotal: 270, lineSellTotal: 570, isOptional: false, isConsumable: true, sortOrder: 6 },
    ],
    variations: [
      { id: 'v1', name: 'Basic', description: 'Standard fixtures', costMultiplier: 0.85 },
      { id: 'v2', name: 'Standard', description: 'Mid-range fixtures', costMultiplier: 1.0 },
      { id: 'v3', name: 'Luxury', description: 'Premium fixtures', costMultiplier: 1.4 },
    ],
    totalCostPrice: 1425,
    totalSellPrice: 2585,
    totalLaborHours: 14,
    defaultMarkupPercentage: 40,
    usageCount: 12,
    lastUsedAt: '2026-01-20T08:00:00Z',
    averageJobProfit: 1160,
    tags: ['renovation', 'bathroom', 'large-job'],
    version: 3,
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2025-12-10T00:00:00Z',
  },
  {
    id: '5',
    name: 'Gas Cooktop Installation',
    description: 'Gas cooktop installation with compliance certificate',
    kitType: 'installation',
    category: 'Gas Fitting',
    status: 'active',
    color: '#EF4444',
    icon: 'Fuel',
    applicableJobTypes: ['Gas Installation', 'Kitchen Renovation'],
    items: [
      { id: 'i1', itemType: 'inventory', itemName: 'Gas Isolator Cock', quantity: 1, unit: 'EA', unitCost: 35, unitSellPrice: 65, lineCostTotal: 35, lineSellTotal: 65, isOptional: false, isConsumable: true, sortOrder: 1 },
      { id: 'i2', itemType: 'inventory', itemName: 'Copper Tube 15mm x 3m', quantity: 2, unit: 'LN', unitCost: 25, unitSellPrice: 45, lineCostTotal: 50, lineSellTotal: 90, isOptional: false, isConsumable: true, sortOrder: 2 },
      { id: 'i3', itemType: 'inventory', itemName: 'Compliance Certificate', quantity: 1, unit: 'EA', unitCost: 25, unitSellPrice: 45, lineCostTotal: 25, lineSellTotal: 45, isOptional: false, isConsumable: true, sortOrder: 3 },
      { id: 'i4', itemType: 'labor', laborType: 'Gas Fitter', itemName: 'Labor - Gas Install', quantity: 2, unit: 'HR', unitCost: 55, unitSellPrice: 110, lineCostTotal: 110, lineSellTotal: 220, isOptional: false, isConsumable: true, sortOrder: 4 },
    ],
    totalCostPrice: 220,
    totalSellPrice: 420,
    totalLaborHours: 2,
    defaultMarkupPercentage: 55,
    usageCount: 31,
    lastUsedAt: '2026-01-30T11:00:00Z',
    averageJobProfit: 200,
    tags: ['gas', 'kitchen', 'compliance'],
    version: 1,
    createdAt: '2025-04-01T00:00:00Z',
    updatedAt: '2025-09-15T00:00:00Z',
  },
];

export const INITIAL_MOVEMENTS: StockMovement[] = [
  { id: 'm1', itemId: 'i1', type: 'In', quantity: 50, timestamp: Date.now() - 86400000 * 5 },
  { id: 'm2', itemId: 'i1', type: 'Out', quantity: 5, timestamp: Date.now() - 86400000, reference: 'j2' },
];
