import bcrypt from 'bcryptjs';

// UUID v4-compatible default for SQLite (matches PostgreSQL gen_random_uuid() format)
const UUID_DEFAULT = "(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2, 3) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2, 3) || '-' || lower(hex(randomblob(6))))";

export function initSQLiteSchema(db) {
  // Enable foreign keys
  db.pragma('foreign_keys = ON');

  const tables = [
    `CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      first_name TEXT,
      last_name TEXT,
      full_name TEXT,
      role TEXT DEFAULT 'technician',
      company_name TEXT,
      phone TEXT,
      is_active INTEGER DEFAULT 1,
      email_verified INTEGER DEFAULT 0,
      team_id INTEGER,
      team_role TEXT DEFAULT 'member',
      invited_by INTEGER,
      invited_at DATETIME,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS categories (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      description TEXT,
      color TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS contacts (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      user_id TEXT,
      type TEXT NOT NULL,
      name TEXT,
      company TEXT,
      company_name TEXT,
      first_name TEXT,
      last_name TEXT,
      email TEXT,
      phone TEXT,
      mobile TEXT,
      address TEXT,
      address_street TEXT,
      address_city TEXT,
      address_state TEXT,
      address_postcode TEXT,
      address_country TEXT,
      city TEXT,
      state TEXT,
      postcode TEXT,
      abn TEXT,
      billing_email TEXT,
      website TEXT,
      primary_contact_name TEXT,
      primary_contact_phone TEXT,
      primary_contact_email TEXT,
      customer_type TEXT,
      tags TEXT,
      default_markup_percentage REAL,
      default_discount_percentage REAL,
      default_payment_terms TEXT,
      custom_payment_days INTEGER,
      status TEXT DEFAULT 'active',
      is_vip INTEGER DEFAULT 0,
      credit_limit REAL,
      internal_notes TEXT,
      preferred_contact_method TEXT,
      billing_address_street TEXT,
      billing_address_city TEXT,
      billing_address_state TEXT,
      billing_address_postcode TEXT,
      notes TEXT,
      is_active INTEGER DEFAULT 1,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS inventory_items (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      user_id TEXT,
      name TEXT NOT NULL,
      description TEXT,
      category TEXT,
      category_id INTEGER,
      quantity REAL DEFAULT 0,
      unit TEXT,
      price REAL,
      cost_price REAL,
      sale_price REAL,
      buy_price_excl_gst REAL,
      buy_price_incl_gst REAL,
      sell_price_excl_gst REAL,
      sell_price_incl_gst REAL,
      location TEXT,
      min_quantity REAL DEFAULT 0,
      max_quantity REAL,
      reorder_level REAL DEFAULT 0,
      reorder_point REAL DEFAULT 0,
      barcode TEXT,
      sku TEXT,
      supplier_id TEXT,
      supplier_code TEXT,
      is_active INTEGER DEFAULT 1,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS location_stock (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id TEXT,
      item_id TEXT NOT NULL,
      location_id INTEGER NOT NULL,
      quantity REAL DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS jobs (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      user_id TEXT,
      job_number TEXT UNIQUE,
      title TEXT,
      builder TEXT,
      customer_id TEXT,
      customer_name TEXT,
      customer_email TEXT,
      customer_phone TEXT,
      job_type TEXT,
      address TEXT,
      job_address TEXT,
      description TEXT,
      status TEXT DEFAULT 'Scheduled',
      priority TEXT DEFAULT 'medium',
      is_picked INTEGER DEFAULT 0,
      assigned_to INTEGER,
      estimated_hours REAL,
      actual_hours REAL,
      quoted_amount REAL,
      actual_amount REAL,
      date TEXT,
      scheduled_date DATE,
      completed_at DATETIME,
      invoiced INTEGER DEFAULT 0,
      development_project_id TEXT,
      development_stage_id TEXT,
      notes TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS job_items (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      job_id INTEGER NOT NULL,
      inventory_item_id INTEGER,
      description TEXT,
      quantity REAL,
      unit_price REAL,
      total REAL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS job_workers (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      job_id TEXT NOT NULL,
      worker_id TEXT NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS job_allocated_items (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      job_id TEXT NOT NULL,
      item_id TEXT NOT NULL,
      quantity REAL NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS quotes (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      user_id TEXT NOT NULL,
      quote_number TEXT UNIQUE,
      customer_id TEXT,
      customer_name TEXT,
      customer_email TEXT,
      customer_phone TEXT,
      customer_address TEXT,
      job_id TEXT,
      title TEXT,
      description TEXT,
      subtotal REAL,
      tax REAL,
      total REAL,
      status TEXT DEFAULT 'draft',
      valid_from TEXT,
      valid_until TEXT,
      discount_type TEXT,
      discount_value REAL,
      discount_amount REAL,
      tax_rate REAL,
      tax_amount REAL,
      default_markup_percentage REAL,
      terms TEXT,
      notes TEXT,
      customer_notes TEXT,
      requires_approval INTEGER DEFAULT 0,
      approved_by TEXT,
      approved_at TEXT,
      rejection_reason TEXT,
      sent_at TEXT,
      viewed_at TEXT,
      responded_at TEXT,
      converted_to_invoice_id TEXT,
      version INTEGER DEFAULT 1,
      parent_quote_id TEXT,
      created_by TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS quote_items (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      quote_id TEXT NOT NULL,
      item_type TEXT DEFAULT 'labor',
      inventory_item_id TEXT,
      item_name TEXT,
      item_description TEXT,
      item_code TEXT,
      description TEXT,
      quantity REAL,
      unit TEXT,
      unit_cost REAL,
      markup_percentage REAL,
      unit_price REAL,
      total REAL,
      line_total REAL,
      profit_margin REAL,
      sort_order INTEGER DEFAULT 0,
      group_name TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS invoices (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      user_id TEXT,
      contact_id TEXT,
      invoice_number TEXT UNIQUE,
      job_id TEXT,
      quote_id TEXT,
      customer_id TEXT,
      customer_name TEXT,
      customer_email TEXT,
      subtotal REAL,
      tax REAL,
      tax_amount REAL,
      total REAL,
      total_amount REAL,
      amount_paid REAL DEFAULT 0,
      status TEXT DEFAULT 'draft',
      issue_date DATE,
      due_date DATE,
      paid_at DATETIME,
      notes TEXT,
      terms TEXT,
      xero_invoice_id TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS invoice_items (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      invoice_id TEXT NOT NULL,
      description TEXT,
      quantity REAL,
      unit_price REAL,
      tax_rate REAL DEFAULT 0,
      line_total REAL,
      total REAL,
      item_type TEXT DEFAULT 'material',
      inventory_item_id TEXT,
      sort_order INTEGER DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS payments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      invoice_id TEXT NOT NULL,
      amount REAL NOT NULL,
      payment_method TEXT,
      payment_date DATETIME,
      reference TEXT,
      notes TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS stock_movements (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id TEXT,
      item_id TEXT,
      inventory_item_id INTEGER,
      type TEXT NOT NULL,
      quantity REAL NOT NULL,
      reference TEXT,
      timestamp DATETIME,
      from_location TEXT,
      to_location TEXT,
      job_id TEXT,
      quote_id TEXT,
      notes TEXT,
      created_by INTEGER,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS locations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id TEXT,
      name TEXT NOT NULL,
      address TEXT,
      type TEXT DEFAULT 'warehouse',
      is_default INTEGER DEFAULT 0,
      is_active INTEGER DEFAULT 1,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS job_templates (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      description TEXT,
      estimated_hours REAL,
      default_price REAL,
      category TEXT,
      is_active INTEGER DEFAULT 1,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS equipment (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      type TEXT,
      model TEXT,
      serial_number TEXT,
      registration TEXT,
      purchase_date DATE,
      purchase_price REAL,
      current_value REAL,
      status TEXT DEFAULT 'active',
      assigned_to INTEGER,
      location TEXT,
      notes TEXT,
      last_service_date DATE,
      next_service_date DATE,
      service_interval_days INTEGER,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS subcontractors (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      user_id TEXT NOT NULL,
      name TEXT NOT NULL,
      type TEXT,
      email TEXT,
      phone TEXT,
      company TEXT,
      address_street TEXT,
      address_city TEXT,
      address_state TEXT,
      address_postcode TEXT,
      address_country TEXT,
      abn TEXT,
      billing_email TEXT,
      website TEXT,
      primary_contact_name TEXT,
      primary_contact_phone TEXT,
      primary_contact_email TEXT,
      tags_json TEXT,
      status TEXT,
      internal_notes TEXT,
      preferred_contact_method TEXT,
      business_name TEXT,
      trading_name TEXT,
      trade_type_json TEXT,
      expertise_json TEXT,
      insurance_documents_json TEXT,
      license_documents_json TEXT,
      availability_status TEXT DEFAULT 'available',
      typical_lead_time INTEGER,
      preferred_job_types_json TEXT,
      service_area_json TEXT,
      hourly_rate REAL,
      daily_rate REAL,
      call_out_fee REAL,
      emergency_contact_name TEXT,
      emergency_contact_phone TEXT,
      bank_account_name TEXT,
      bank_bsb TEXT,
      bank_account_number TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS kits (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      user_id TEXT NOT NULL,
      name TEXT NOT NULL,
      description TEXT,
      kit_type TEXT,
      category TEXT,
      status TEXT DEFAULT 'draft',
      color TEXT,
      icon TEXT,
      applicable_job_types_json TEXT,
      items_json TEXT,
      variations_json TEXT,
      total_cost_price REAL,
      total_sell_price REAL,
      total_labor_hours REAL,
      default_markup_percentage REAL,
      usage_count INTEGER DEFAULT 0,
      last_used_at TEXT,
      average_job_profit REAL,
      average_completion_time REAL,
      tags_json TEXT,
      version INTEGER DEFAULT 1,
      parent_kit_id TEXT,
      created_by TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS kit_items (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      kit_id INTEGER NOT NULL,
      inventory_item_id INTEGER,
      quantity REAL NOT NULL,
      unit_cost REAL,
      unit_sale REAL
    )`,
    `CREATE TABLE IF NOT EXISTS purchase_orders (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      po_number TEXT UNIQUE,
      supplier_id INTEGER,
      status TEXT DEFAULT 'draft',
      subtotal REAL,
      tax REAL,
      shipping REAL,
      total REAL,
      notes TEXT,
      expected_delivery DATE,
      created_by INTEGER,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS purchase_order_items (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      purchase_order_id INTEGER NOT NULL,
      inventory_item_id INTEGER,
      description TEXT,
      quantity INTEGER,
      quantity_received INTEGER DEFAULT 0,
      unit_price REAL,
      line_total REAL
    )`,
    `CREATE TABLE IF NOT EXISTS suppliers (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      contact_id INTEGER,
      account_number TEXT,
      payment_terms TEXT,
      lead_time_days INTEGER,
      min_order_amount REAL,
      rating REAL,
      is_preferred INTEGER DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS email_queue (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      to_address TEXT NOT NULL,
      subject TEXT NOT NULL,
      body TEXT,
      template_id TEXT,
      template_data TEXT,
      status TEXT DEFAULT 'pending',
      priority INTEGER DEFAULT 5,
      scheduled_at DATETIME,
      sent_at DATETIME,
      error_message TEXT,
      retry_count INTEGER DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS scheduled_tasks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      description TEXT,
      cron_expression TEXT,
      is_active INTEGER DEFAULT 1,
      last_run_at DATETIME,
      next_run_at DATETIME,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS activity_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER,
      action TEXT,
      entity_type TEXT,
      entity_id INTEGER,
      details TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS teams (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      owner_id TEXT,
      subscription_tier TEXT DEFAULT 'team',
      max_users INTEGER DEFAULT 5,
      settings TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS team_members (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      team_id TEXT NOT NULL,
      user_id TEXT NOT NULL,
      role TEXT DEFAULT 'member',
      joined_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS team_invitations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      team_id TEXT NOT NULL,
      email TEXT NOT NULL,
      role TEXT DEFAULT 'member',
      token TEXT UNIQUE NOT NULL,
      invited_by TEXT,
      message TEXT,
      status TEXT DEFAULT 'pending',
      expires_at DATETIME,
      accepted_at DATETIME,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS franchise_locations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      network_id INTEGER,
      territory_id INTEGER,
      name TEXT NOT NULL,
      code TEXT,
      status TEXT DEFAULT 'active',
      address TEXT,
      city TEXT,
      state TEXT,
      postal_code TEXT,
      country TEXT,
      phone TEXT,
      email TEXT,
      website TEXT,
      currency TEXT DEFAULT 'GBP',
      opened_date DATE,
      settings TEXT,
      owner_user_id TEXT,
      monthly_revenue REAL DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS franchise_territories (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      network_id INTEGER,
      name TEXT NOT NULL,
      assigned_to_location_id INTEGER,
      matched_territory_id INTEGER,
      is_available INTEGER DEFAULT 1,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS development_stages (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      user_id TEXT,
      project_id TEXT,
      name TEXT NOT NULL,
      stage_type TEXT,
      status TEXT DEFAULT 'pending',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS quote_history (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      quote_id TEXT NOT NULL,
      user_id TEXT,
      action TEXT NOT NULL,
      old_status TEXT,
      new_status TEXT,
      notes TEXT,
      total_at_action REAL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS quote_templates (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      user_id TEXT NOT NULL,
      name TEXT NOT NULL,
      description TEXT,
      default_terms TEXT,
      default_customer_notes TEXT,
      default_validity_days INTEGER DEFAULT 30,
      default_markup_percentage REAL DEFAULT 0,
      job_type TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS quote_template_items (
      id TEXT PRIMARY KEY DEFAULT ${UUID_DEFAULT},
      template_id TEXT NOT NULL,
      item_type TEXT DEFAULT 'material',
      inventory_item_id TEXT,
      item_name TEXT NOT NULL,
      item_description TEXT,
      default_quantity REAL DEFAULT 1,
      unit TEXT DEFAULT 'EA',
      default_markup_percentage REAL DEFAULT 0,
      sort_order INTEGER DEFAULT 0,
      group_name TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS quote_number_sequence (
      user_id TEXT PRIMARY KEY,
      prefix TEXT DEFAULT 'Q',
      current_number INTEGER DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS franchise_networks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      is_active INTEGER DEFAULT 1,
      code TEXT,
      legal_name TEXT,
      description TEXT,
      logo_url TEXT,
      primary_color TEXT,
      secondary_color TEXT,
      accent_color TEXT,
      headquarters_address TEXT,
      headquarters_city TEXT,
      headquarters_state TEXT,
      headquarters_postal_code TEXT,
      headquarters_country TEXT DEFAULT 'United Kingdom',
      phone TEXT,
      email TEXT,
      website TEXT,
      default_currency TEXT DEFAULT 'GBP',
      default_timezone TEXT DEFAULT 'Europe/London',
      fiscal_year_start INTEGER DEFAULT 1,
      royalty_type TEXT DEFAULT 'percentage',
      royalty_percentage REAL,
      royalty_fixed_amount REAL,
      franchise_fee REAL,
      royalty_tiers TEXT,
      white_label_config TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`
  ];

  for (const sql of tables) {
    try {
      db.exec(sql);
    } catch (err) {
      console.error('Error creating table:', err.message);
      console.error('SQL:', sql.substring(0, 100));
    }
  }

  console.log('✅ SQLite schema initialized');

  try {
    const userCount = db.prepare('SELECT COUNT(*) as count FROM users').get();
    if (userCount.count === 0) {
      const hashedPassword = bcrypt.hashSync('admin123', 10);

      db.prepare(`
        INSERT INTO users (email, password_hash, first_name, last_name, full_name, role)
        VALUES (?, ?, ?, ?, ?, ?)
      `).run('admin@plumbpro.local', hashedPassword, 'Admin', 'User', 'Admin User', 'admin');

      console.log('✅ Default admin user created (admin@plumbpro.local / admin123)');
    }
  } catch (err) {
    console.error('Error creating admin user:', err.message);
  }

  try {
    const locationCount = db.prepare('SELECT COUNT(*) as count FROM locations').get();
    if (locationCount.count === 0) {
      db.prepare(`
        INSERT INTO locations (name, type) VALUES (?, ?)
      `).run('Main Warehouse', 'warehouse');
      console.log('✅ Default location created');
    }
  } catch (err) {
    console.error('Error creating default location:', err.message);
  }
}
